image: node:alpine

stages:
  - install
  - build
  - test
  - publish

dependencies:
  stage: install
  script:
    - npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

build:
  stage: build
  before_script:
    - sed -ri "s|\'PACKAGE_VERSION\'|\'$(node -p -e "require('./package.json').version")\'|" src/constants.ts # replace PACKAGE_VERSION with package.json version
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull # https://docs.gitlab.com/ee/ci/yaml/#cachepolicy
  artifacts:
    paths:
      - dist/

publish:
  stage: publish
  when: manual
  only:
    - master
  script:
    - npm publish --registry=http://registry.fini.city:8081/repository/npm-private/
  artifacts:
    paths:
      - dist/
